### ISSUE TITLE
Zoho form issue

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#10]
The scroll occur in contact form, pop up form at all responsive
![image](https://user-images.githubusercontent.com/91531533/178490894-2b87ff01-9f44-40ad-bf4b-04df4c0a71b9.png)
![image](https://user-images.githubusercontent.com/91531533/178491163-84e5beb7-bff0-43e9-863e-a4cbc508a66e.png)
![image](https://user-images.githubusercontent.com/91531533/178491432-77097236-61e7-4e83-900a-d88a1a22bf7d.png)

**Comment by Kaviraj222** [comment]
![screencapture-localhost-4700-contact-us-2022-07-13-18_28_33](https://user-images.githubusercontent.com/100666708/178739319-b529e7c3-c2f1-4c2a-a20e-0a99de1916d7.png)
![image](https://user-images.githubusercontent.com/100666708/178739521-663a5f16-15c5-4f31-95c5-818f1019a587.png)
![image](https://user-images.githubusercontent.com/100666708/178739666-3956d4fe-a3de-46c9-991a-57fe2cb51555.png)
The scroll occur in contact form, pop up form at all responsive issues fixed.

**Comment by Viji-K** [comment]
We moved to GHL form. This issue closed
