### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#14]
When we click the blog inner, the 404 page is loaded.
![image](https://user-images.githubusercontent.com/91531533/184143734-aee12658-897c-47a0-b257-ee402b966c6e.png)

**Comment by Kaviraj222** [comment]
![image](https://user-images.githubusercontent.com/100666708/184337579-8b92ef67-96f3-44fc-9079-1377a25c65ef.png)
issue fixed.

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
