### ISSUE TITLE
Banner text less readability

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#15]
In home page, 
1. The text is less readability in banner section from 769 to 999 dimensions
![image](https://user-images.githubusercontent.com/91531533/184144043-fdea3c9e-725f-4f7e-99dc-4c029afc037a.png)

2. The text and image overlapped in all responsive
![image](https://user-images.githubusercontent.com/91531533/184144772-80d796b1-159e-4ee2-af32-03cda2e2a51a.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/188452559-fb59ec04-d56f-4c2a-9a31-ebb890de3bd1.png)
![image](https://user-images.githubusercontent.com/91717900/188452574-d23b591f-15de-4728-ba28-2514f1a3684a.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188883324-f30ba59c-6c76-422b-8250-27e10c0b84c5.png)
![image](https://user-images.githubusercontent.com/91531533/188883463-36ed0eba-7345-4fcf-bcf3-1954e787437d.png)
