### ISSUE TITLE
Slider icon missing

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#16]
In contact page, the slider icon is missing from 601 to 767  dimensions
![image (224)](https://user-images.githubusercontent.com/91531533/184145329-5c1c9193-4b81-4ab7-a21c-75feed17d678.png)

**Comment by Swamifsd** [comment]
Issues are fixed 
![image](https://user-images.githubusercontent.com/91717900/188452386-83bceab8-1536-4fc1-85b8-1a7a8d88e175.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188882592-90b13eff-c6d7-471f-b6e0-168c64d0f75e.png)
