### ISSUE TITLE
Align Product details in cart

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#17]
1.Align the cart page product details and fix the image size should be in rounded square at all mobile responsive like checkout page.
![image](https://user-images.githubusercontent.com/91531533/184355258-8f4af78b-d16f-4c3c-ba3d-5693be2e5441.png)

**Comment by Viji-K** [comment]
![image](https://user-images.githubusercontent.com/91531533/185389468-9d2b2764-7763-4d65-9908-27567ecf64d9.png)

**Comment by Swamifsd** [comment]
Issues are fixed

![image](https://user-images.githubusercontent.com/91717900/188270199-08b27c08-db40-4339-93c5-1eb25fff221a.png)
![image](https://user-images.githubusercontent.com/91717900/188270201-8a77ba59-4b0f-4844-bb18-c50d127cd65d.png)
![image](https://user-images.githubusercontent.com/91717900/188270232-83504b6e-e9c8-46c9-92fb-bdd6a7944e95.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188883688-9dc05936-65f2-45af-b37f-62c03077607f.png)
![image](https://user-images.githubusercontent.com/91531533/188883853-9b3178b6-8b3d-49f5-8f5e-3122b76b5fd9.png)
