### ISSUE TITLE
Align About us page

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#18]
In about us page,
1.Fix the button size from 601 to 767 dimension and 1025 to 1183 dimension
2. content shown within the image(height) otherwise the read more button should be enable
![image](https://user-images.githubusercontent.com/91531533/184355557-c57da3b0-96a6-4bed-8463-0fe174231eff.png)

**Comment by Swamifsd** [comment]
Issue No.1 is fixed
Issue No.2 is not a read more button. It's redirected to other page
![image](https://user-images.githubusercontent.com/91717900/188452906-40e31cf0-76ed-436a-8dae-b55963a8837e.png)
![image](https://user-images.githubusercontent.com/91717900/188452930-04318fc3-e999-4cf0-80c9-02294cb40291.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
