### ISSUE TITLE
Popup cart alignment

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#19]
In popup cart,
1.The close icon is not shown from 320 to 600 dimension
2.The popup cart is misaligned in iOS devices
![image (229)](https://user-images.githubusercontent.com/91531533/184356130-8c3dc6d3-e52e-4ffd-a780-18e3df58831d.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/188647931-f4f91a01-5dda-4ef7-899f-1862913071ab.png)
![image](https://user-images.githubusercontent.com/91717900/188647948-b4944436-c169-4a6c-aec8-ad6646b48270.png)
![image](https://user-images.githubusercontent.com/91717900/188647965-6e747c30-b397-4ab0-aa5e-974f7064bb9e.png)
![image](https://user-images.githubusercontent.com/91717900/188648004-826fb45f-5d35-40bd-ad62-b613bdfae208.png)

**Comment by Viji-K** [comment]
![image](https://user-images.githubusercontent.com/91531533/189138870-60691cfa-e29e-4c14-8648-6d0693278315.png)
![image](https://user-images.githubusercontent.com/91531533/189138923-468c2849-5cce-471d-a10e-68e9128fb744.png)
![image](https://user-images.githubusercontent.com/91531533/189139243-e74a2fcf-9029-4c8e-ac4a-bff257d47350.png)
![image](https://user-images.githubusercontent.com/91531533/189139561-1e21d12e-94e1-489f-ba31-ca6916816167.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
