### ISSUE TITLE
Button overlapping

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#22]
In banner section, the button and scroll down icon is overlapped in iPhone 5SE
![image (234)](https://user-images.githubusercontent.com/91531533/185394231-9c79b1c3-9189-4bf2-b912-5a68827182f2.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/191012708-b24d1963-1635-4fe8-a163-a5aea9e97581.png)
