### ISSUE TITLE
Change cursor pointer

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#23]
In footer,

1. Click FOLLOW US. The 404 page is redirected. Rid the link for FOLLOW US
![image (236)](https://user-images.githubusercontent.com/91531533/185395617-16023c97-0e19-49e0-8331-3ae41aaf6b47.png)

2.Change the cursor pointer as hand pointer while hover over the social icons
![image (235)](https://user-images.githubusercontent.com/91531533/185394778-d328e752-2e42-4e54-8030-a5bcc9d600cb.png)

**Comment by nowfal989427** [comment]
- Have removed the anchor link in the follows us a text
- Have changed the hover effect in the follows us a text 
- Have added the hover effect for all social media links

![image](https://user-images.githubusercontent.com/93910501/187916858-6d2826db-2d14-45a5-9194-3f4cd2cc80df.png)

**Comment by Viji-K** [comment]
When we click the social icon, the page is opened in new tab but the same page is redirected to 404 page
![image](https://user-images.githubusercontent.com/91531533/188267708-0e84337b-1123-4992-992a-e06b2d5a83a0.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
