### ISSUE TITLE
Scroll down icon not working

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#24]
In home new page, the scroll down icon is not working in banner section
![image (238)](https://user-images.githubusercontent.com/91531533/185398065-22c59fb6-a988-4df0-a26b-45217f28108b.png)

**Comment by nowfal989427** [comment]
- Have added the scroll top id and it's now working fine

![image](https://user-images.githubusercontent.com/93910501/187898342-fa05bd34-dec1-46ad-baa5-b1209df6f566.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
