### ISSUE TITLE
My account menu issue

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#25]
When we click the user icon after login, the sub menu is not displayed within the screen size from 1030 to 1574 dimensions
![image (239)](https://user-images.githubusercontent.com/91531533/185398582-8a20657f-0c61-4115-b471-443efc95c7d0.png)

**Comment by nowfal989427** [comment]
- Have aligned to the drop-down menu at the middle view 

![image](https://user-images.githubusercontent.com/93910501/187889760-b7f8ffd8-1156-4ee4-b8ec-80913c575807.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188269149-43c671bb-ea16-4618-96ac-27a3ed2160bf.png)
