### ISSUE TITLE
Need space

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#26]
1. In shop inner page, give space above the image from 320 to 767 dimension
![image (240)](https://user-images.githubusercontent.com/91531533/185399633-adaab4e7-3ebe-49f6-b320-0baf04e139e0.png)

**Comment by nowfal989427** [comment]
- Have to give the space above the cta section.

![image](https://user-images.githubusercontent.com/93910501/187856191-31731e71-b257-4281-b892-8c2bf781bd6d.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188269009-de9fe84f-98d2-40c6-b75f-da42ba40e64b.png)
