### ISSUE TITLE
Faq page 

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#27]
Fix the following issue. Refer screenshot
![image (242)](https://user-images.githubusercontent.com/91531533/185399931-27416647-07f4-4951-a897-18de24032543.png)

**Comment by nowfal989427** [comment]
- Have removed the unwanted space on the FAQ page

![image](https://user-images.githubusercontent.com/93910501/187845842-5a793a2a-e448-42cd-8f4c-bf80f8fd41b9.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/188262935-04633d89-14bb-4558-9f73-c156274a376e.png)
