### ISSUE TITLE
Menu items in iOS device 

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#31]
In hamburger menu, we couldn't able to click the menu items at all iPhone and iPad (Lower models and lower version)
![image](https://user-images.githubusercontent.com/91531533/185847439-ecb311c4-cbb4-46a6-81b1-1dadf7c98a88.png)

**Comment by Swamifsd** [comment]
Issues are fixed

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
