### ISSUE TITLE
Page not fit with screen size

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#34]
The cart, login, register, forgot, my account, website disclaimer page didn't fit with the entire screen at above iPad responsive and large screen.
![image](https://user-images.githubusercontent.com/91531533/188271014-3d5b3e18-665d-4aac-928f-b01057b56654.png)
![image](https://user-images.githubusercontent.com/91531533/188271020-eda7198c-f31d-4408-8157-e2d0cdd7d1c4.png)
![image](https://user-images.githubusercontent.com/91531533/188271032-0f6d784f-86ee-4198-ab2c-af0d37f95c73.png)
![image](https://user-images.githubusercontent.com/91531533/188271050-1dc30174-ab85-4f4b-b41e-eaa5f5d44207.png)
![image](https://user-images.githubusercontent.com/91531533/188271057-639d1555-5da1-43b5-bf31-88bcd54e900f.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/188453197-84611fc0-0d2e-48f2-b156-7ab4d401e2c6.png)
![image](https://user-images.githubusercontent.com/91717900/188453204-0a82f5be-be4e-4573-855a-358fec97ac34.png)
![image](https://user-images.githubusercontent.com/91717900/188453218-468c74f7-d1d8-4c1d-89ee-95ee1a165d8a.png)
![image](https://user-images.githubusercontent.com/91717900/188453233-b17a7f5b-aea6-42b1-a820-ee555ea9d719.png)
![image](https://user-images.githubusercontent.com/91717900/188453241-d7698e4f-aa5d-499b-a707-2e79ed1ea929.png)
