### ISSUE TITLE
Reloading the account page 

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#40]
In my account page, it took more time to load the order history. Add loading icon.
When we reloaded the my account page, sometimes its redirected to login page. It occurs, we refresh the page again and again

**Comment by Kaviraj222** [comment]
issue fixed

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/189339689-e775fffc-a570-476f-a942-137b27e52e97.png)
