### ISSUE TITLE
Instagram alignment

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#41]
In blog page, align equal space between the Instagram post 
![image (260)](https://user-images.githubusercontent.com/91531533/189349592-95e8db9b-912c-4104-8c48-2d68f9ac0ccc.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/189372419-a93f984d-074e-4644-8e94-9a199d11f18f.png)
![image](https://user-images.githubusercontent.com/91717900/189372429-ae6d8bb4-edff-4434-8457-112254d2ebf4.png)
![image](https://user-images.githubusercontent.com/91717900/189372441-803c8df3-ac44-4a90-98aa-990e550504ba.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
