### ISSUE TITLE
Title not shown in login pages

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#45]
The title didn't shown in login, register and forgot password page

![image](https://user-images.githubusercontent.com/91531533/190409113-53f22ee0-b66e-44bc-83a9-a43d23543c51.png)
![image](https://user-images.githubusercontent.com/91531533/190409148-02afad36-22e7-4444-bdfd-1c345731440b.png)
![image](https://user-images.githubusercontent.com/91531533/190409168-c19e6073-e145-44cd-90c1-9939225542f1.png)

**Comment by Kaviraj222** [comment]
![image](https://user-images.githubusercontent.com/100666708/190959467-8a7917a1-f5f3-441b-938b-8e2513401fb8.png)
![image](https://user-images.githubusercontent.com/100666708/190959537-e29f8b1c-1116-4fca-bce7-b28de41d63c7.png)
![image](https://user-images.githubusercontent.com/100666708/190959573-4d8aab16-d3e6-447b-837d-37e4768fbb2a.png)
issue fixed.

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/191262093-c6c38556-9a44-4578-abb4-41f8409bed90.png)
