### ISSUE TITLE
GHL form alignment

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#51]
In contact page, fix the form height while click the submit button without input in iPhone devices.
![image](https://user-images.githubusercontent.com/91531533/200297845-6c6acbe6-3c6b-41ce-b1ba-2129a0253526.png)

**Comment by Balakumar360** [comment]
Issues are fixed

**Comment by Viji-K** [comment]
The above issues were fixed, verified and closed
![image (426)](https://user-images.githubusercontent.com/91531533/204227628-7cc7b6db-1068-4f3e-8c4c-c1035a9fca4b.png)
![image (425)](https://user-images.githubusercontent.com/91531533/204227647-155cfee6-ffd0-4317-ad7c-c09fa9aad38d.png)
