### ISSUE TITLE
Close icon in iOS

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#54]
In cart page, fix the close icon shape in iOS devices
![image](https://user-images.githubusercontent.com/91531533/201082068-792a8890-16d7-4679-9f16-aa5c65f97b2d.png)
![image](https://user-images.githubusercontent.com/91531533/201082109-b1d2f92b-4623-419f-b1e5-13eb6eb1093d.png)

**Comment by Ismail360** [comment]
Issue fixed.
![image](https://user-images.githubusercontent.com/74038850/202697154-56922b06-57ae-4fc6-8beb-f972907f8367.png)

**Comment by Ismail360** [comment]
![image](https://user-images.githubusercontent.com/74038850/202699193-ed5510c1-19b3-475d-aa8e-1ba31ef34ad0.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/203785239-bab599fb-090a-44f9-a964-3c63cf87a244.png)
![image](https://user-images.githubusercontent.com/91531533/203785279-37d1d2cb-bb4e-419b-97c7-8b9abf95a799.png)
![image](https://user-images.githubusercontent.com/91531533/203785370-c6a1bb37-53b0-466b-b45e-736cf3d00488.png)
![image](https://user-images.githubusercontent.com/91531533/203785788-a16f06b4-0c70-4fc9-b3b6-847b50f9caf3.png)
![image](https://user-images.githubusercontent.com/91531533/203785839-6e63986b-e53f-49a4-ab8a-f38f24cd2e51.png)
