### ISSUE TITLE
Title alignment in Asta page

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#55]
In What is Asta page, align the title within the screen in  the following iOS devices
iPhone 6s plus v11,  iPhone se v11, iPhone 8 plus v12,  iPhone x v11, iPhone 6s v12, iPhone 7 v12, iPhone xs max v12, iPad 9 v14 , iPad pro 9 v11, iPad 8 v16, iPad 7 v13
![image](https://user-images.githubusercontent.com/91531533/201082431-712ce425-2c42-4895-94e4-a645708d1f3a.png)
![image](https://user-images.githubusercontent.com/91531533/201082463-16761759-bdfd-4c7d-bd59-7e6ada4a7d70.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/203333664-c8f7d6fe-b0e6-46aa-a8a9-ac9f586378ba.png)
![image](https://user-images.githubusercontent.com/91717900/203333675-5d4b011d-5741-4573-abca-4ca0c9a0d596.png)
![image](https://user-images.githubusercontent.com/91717900/203333655-2f4bf43d-cf81-4967-931e-978ba4084f4c.png)
![image](https://user-images.githubusercontent.com/91717900/203333687-2aa286f8-9ca5-4fe3-a121-543b7eafb382.png)
![image](https://user-images.githubusercontent.com/91717900/203333690-64aeb0eb-1ead-4ee2-865b-5a05df94fe4a.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/203784309-047bb860-bbad-4b89-98ec-dabf94f5b545.png)
![image](https://user-images.githubusercontent.com/91531533/203784920-d052d810-6bfa-4098-b54e-726ddd2ea97c.png)
