### ISSUE TITLE
Quantity less readability

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#56]
- In cart page and popup cart, the quantity is less readability in iOS devices
![image](https://user-images.githubusercontent.com/91531533/201083820-a3cae303-1123-4561-948e-d1b46a0d55d0.png)
![image](https://user-images.githubusercontent.com/91531533/201083903-3e00bd9c-df0e-4bad-b3d0-755956e05cc2.png)
![image](https://user-images.githubusercontent.com/91531533/201084195-89c32f22-c476-417c-98e8-95e415ff8231.png)

**Comment by Ismail360** [comment]
Issue fixed.
![image](https://user-images.githubusercontent.com/74038850/202636810-c9d649a3-9573-4cfd-972e-daa0936166f3.png)
![image](https://user-images.githubusercontent.com/74038850/202637122-56763005-acd1-465e-abdc-68203ccd35eb.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/203785978-6f57f2ef-e011-46f0-93b8-4794ac7f330c.png)
![image](https://user-images.githubusercontent.com/91531533/203786010-edf622d9-dc2c-484f-9f7d-b88b2721baa6.png)
![image](https://user-images.githubusercontent.com/91531533/203786044-e5e0e3c1-943d-4568-825f-656961646623.png)
![image](https://user-images.githubusercontent.com/91531533/203786061-9e73deae-5df9-45c3-b871-6abd20e2dd37.png)
![image](https://user-images.githubusercontent.com/91531533/203786092-28383d1e-7e76-449e-a4a2-d1484415788b.png)
