### ISSUE TITLE
Blog post in home page

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#58]
In home page, align the blog post height equally in all iPad and Mac devices.

![image (402)](https://user-images.githubusercontent.com/91531533/201091212-6f6e107a-f155-491e-bc84-6164f74bc62c.png)
![image](https://user-images.githubusercontent.com/91531533/201091219-c260a75a-c4f7-450c-baef-6d7fb31c51da.png)
![image](https://user-images.githubusercontent.com/91531533/201090687-06d6c479-cb8c-42b5-a30c-47a48ca168be.png)

**Comment by Balakumar360** [comment]
Issues are fixed

**Comment by Balakumar360** [comment]
Issues are fixed
![Untitled](https://user-images.githubusercontent.com/117428602/204224841-61a58cb9-88a7-415d-972c-b9d29a46a68b.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image (423)](https://user-images.githubusercontent.com/91531533/204228010-7528a147-6322-45c0-bcf2-795fae524213.png)
![image (424)](https://user-images.githubusercontent.com/91531533/204228032-9428d39c-7e4b-4c4c-a08d-9e33971c868c.png)
![image (428)](https://user-images.githubusercontent.com/91531533/204228241-243906db-bb54-4cef-bae9-577db035217e.png)
![image (427)](https://user-images.githubusercontent.com/91531533/204228285-3503c443-7c8c-4a8a-88a7-579cdca94048.png)
