### ISSUE TITLE
Icon effect missing

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#59]
In Home, Shop and Asta page, the logo effect is missing in the following iPhone devices
iPhone SEV11, iPhone 8plusv12, iPhone x v11, iPhone 6s v12, iPhone 7 v12, iPhone XS Max v12, iPhone 6S Plus v11

![image](https://user-images.githubusercontent.com/91531533/202366081-728519b9-fd40-4517-aa73-f7a4065bb83b.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/203067368-342af128-3564-422f-b467-978198bd6ec6.png)
![image](https://user-images.githubusercontent.com/91717900/203067395-c1c913f0-8567-4411-bb5a-73e092573157.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
https://user-images.githubusercontent.com/91531533/203788243-cc948261-1833-47e3-b46b-f111dc5cdc69.mp4
