### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#60]
In home page, the hover text not shown when we click the image in the following devices
 **iPhone 8plus, iPhone x, iPhone 6s v12, iPhone 7 v12,  iPhone XS Max v12**
![image](https://user-images.githubusercontent.com/91531533/202372280-38837042-1d88-4724-84d6-ff636e727e78.png)
![image](https://user-images.githubusercontent.com/91531533/202373345-d96247e6-c1c0-4264-8138-bf3aa65dc1eb.png)
![image](https://user-images.githubusercontent.com/91531533/202373745-5a6dcecf-df68-4349-afbb-60f9cba5803c.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/203065129-e641cf66-9ec2-4a59-a83c-0f5e1d76bd8b.png)
![image](https://user-images.githubusercontent.com/91717900/203065143-5a02fd58-ede2-48a3-bc96-5a9a0d730e1a.png)

**Comment by Viji-K** [comment]
The above issue fixed, verified and closed
![image](https://user-images.githubusercontent.com/91531533/203775462-ed73eb62-089e-4e6e-965a-45a298aa946f.png)
![image](https://user-images.githubusercontent.com/91531533/203775508-c8db9127-313d-405a-a1a0-5bf4aee3caf2.png)
![image](https://user-images.githubusercontent.com/91531533/203775542-71057129-098e-4f24-8f1f-c5cda47f63db.png)
