### ISSUE TITLE
Category and tag page

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#64]
In category and tag page,

- The category title is not shown
- Maintain space between "back" and category title or tag title
- Give space between the rows of blog post

![image](https://user-images.githubusercontent.com/91531533/203535439-15d205e5-8f2c-45d7-9bcc-21dbf892f1b0.png)

**Comment by Swamifsd** [comment]
Issues are fixed
![image](https://user-images.githubusercontent.com/91717900/203969982-30a65408-c6c2-4e41-94b2-8f0c777803a1.png)
![image](https://user-images.githubusercontent.com/91717900/203970009-45be7c75-0076-47de-81d6-db9e3a41fd47.png)
![image](https://user-images.githubusercontent.com/91717900/203970038-711ac1be-25fd-499b-9e48-6476eeed0795.png)
![image](https://user-images.githubusercontent.com/91717900/203970076-d0b8ad8a-6122-4046-bbcd-635db0ced9de.png)
![image](https://user-images.githubusercontent.com/91717900/203970108-1d22a78e-5d09-4a10-9393-328b2b27450a.png)

**Comment by Viji-K** [comment]
The above issue fixed in category page
![image](https://user-images.githubusercontent.com/91531533/204281586-7b5200f5-a3b0-4777-a22f-bc1dff395811.png)
