### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#7]
Clinical studies page,
![image](https://user-images.githubusercontent.com/91531533/178485443-b3f5ad77-9f25-4b02-82b1-a6e80b9b0426.png)
![image](https://user-images.githubusercontent.com/91531533/178485538-63f962f5-6db4-469e-a483-7e6732dd769b.png)

Brain workout page
![image](https://user-images.githubusercontent.com/91531533/178486212-abbb49b0-9cce-4da3-91fd-5aea9cdb5a45.png)
![image](https://user-images.githubusercontent.com/91531533/178486225-d23824e5-c45c-4ec1-b140-8e219cf360c3.png)

Home page
![image](https://user-images.githubusercontent.com/91531533/178487698-79325545-a941-44ec-b293-5e3be4c81d5f.png)

Popup cart
![image (66)](https://user-images.githubusercontent.com/91531533/178488129-2bd087a7-75bd-46fc-8c6e-a4bc34dfd40e.png)

Cart page
![image (65)](https://user-images.githubusercontent.com/91531533/178487984-5f6da334-0aa5-4aba-872b-c2c0cbea1242.png)

**Comment by Kaviraj222** [comment]
![image](https://user-images.githubusercontent.com/100666708/178691834-a9f66118-3d47-4207-8bfa-1ef4b725e4c5.png)
![image](https://user-images.githubusercontent.com/100666708/178693027-81c7f1e0-787c-4fbb-8cd8-57b915d09102.png)
![image](https://user-images.githubusercontent.com/100666708/178693200-996dc586-c2fa-432d-8ccc-708f40b76e4f.png)
![image](https://user-images.githubusercontent.com/100666708/178693297-dc52cc5d-e073-40fb-89b8-52990da25b71.png)
![image](https://user-images.githubusercontent.com/100666708/178693378-2a477310-9507-49ad-8951-11a33cd9336f.png)
Language changed.

**Comment by Viji-K** [comment]
The above pages language changed, verified and closed
