### ISSUE TITLE
Logo issue

### ISSUE THREAD

**Issue by Viji-K** [9mmenergydrink/ninemmenergy-brazil-front-end#9]
- In home page, fix the logo image size

![image](https://user-images.githubusercontent.com/91531533/178488262-efd07f60-1ec5-4bc2-b81f-73b5162ea856.png)

- In header, the "Beynod Energy"(font color white) missing in  9MM logo
![image](https://user-images.githubusercontent.com/91531533/178490530-b665134e-1829-4dea-a14f-7fa07eff48cf.png)

**Comment by Kaviraj222** [comment]
![image](https://user-images.githubusercontent.com/100666708/178653797-06ffb410-12d6-46d8-a3f8-eb0bf5d23194.png)
![image](https://user-images.githubusercontent.com/100666708/178653845-5e03f052-aa9c-4368-b819-c8df5dcb4916.png)
1. Home page, logo image size issue fixed.
2. header, the "Beynod Energy"(font color white) missing in 9MM logo fixed.
